Updated tools

diff --git a/tools/quickpile b/tools/quickpile
--- a/tools/quickpile
+++ b/tools/quickpile
@@ -1,4 +1,16 @@
+set -e
+touch "$HOME/.quickpilerc"
 NAME="$1"
-BUILD_DIR="$(pwd)"
+BUILD_DIR="$(cat $HOME/.quickpilerc)"
 BUILD_NAME="${NAME%.*}"
-clang++ -O2 "$NAME" -o "$BUILD_DIR/${BUILD_NAME}_compiled"
+if [ "$1" = "--configure" ]; then
+    printf 'which directory do you wish for me to live in: '
+    read conf
+    echo "$conf" > "$HOME/.quickpilerc"
+    exit 0
+fi
+if [ -z "$BUILD_DIR" ]; then
+    echo "Error: .quickpilerc couldnt be found. make sure \$HOME is set and .quickpilerc is configured"
+    exit 1
+fi
+clang++ -O2 "$BUILD_DIR/$NAME" -o "$BUILD_DIR/${BUILD_NAME}_compiled"
diff --git a/tools/run b/tools/run
--- a/tools/run
+++ b/tools/run
@@ -1,6 +1,6 @@
 set -euo pipefail
 
-if [[ -z "${1:-}" ]]; then
+if [ -z "${1:-}" ]; then
     echo "Please provide a file"
     exit 1
 fi
@@ -11,16 +11,28 @@ BASE="$(basename -- "$INPUT")"
 NAMEALT="${BASE%.*}"
 
 # Directory where this script lives
-DIR="$(pwd)"
-
+touch "$HOME/.quickpilerc"
+DIR="$(cat $HOME/.quickpilerc)"
+if [ "$1" = "--configure" ]; then
+    printf 'which directory do you wish for me to live in: '
+    read conf
+    echo "$conf" > "$HOME/.quickpilerc"
+    exit 0
+fi
+if [ -z "$DIR" ]; then
+    echo "Error: .quickpilerc couldnt be found. make sure \$HOME is set and accessable"
+    exit 1
+fi
 CAND1="$DIR/$BASE"
 CAND2="$DIR/${NAMEALT}_compiled"
 
 # Prefer an executable with the exact name, else the _compiled one
-if [[ -x "$CAND1" ]]; then
-    exec "$CAND1" "${@:2}"
-elif [[ -x "$CAND2" ]]; then
-    exec "$CAND2" "${@:2}"
+if [ -x "$CAND1" ]; then
+    shift
+    exec "$CAND1" "$@"
+elif [ -x "$CAND2" ]; then
+    shift
+    exec "$CAND2" "$@"
 else
     echo "file does not exist or is not executable: '$CAND1' or '$CAND2'"
     exit 1
